//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrivalStations_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArrivalStations_TBL()
        {
            this.Governorates_TBL = new HashSet<Governorates_TBL>();
            this.Students_TBL = new HashSet<Students_TBL>();
        }
    
        public int Id { get; set; }
        public string ArriName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Transport_Id { get; set; }
    
        public virtual Transport_TBL Transport_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Governorates_TBL> Governorates_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students_TBL> Students_TBL { get; set; }
    }
}
