//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_TBL
    {
        public int Id { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public string Part { get; set; }
        public int User_Id { get; set; }
    
        public virtual Users_TBL Users_TBL { get; set; }
    }
}
