//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Sanctions_TBL
    {
        public int Id { get; set; }
        public int Student_Id { get; set; }
        public int Sanctions_Id { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual Students_TBL Students_TBL { get; set; }
        public virtual Sanctions_TBL Sanctions_TBL { get; set; }
    }
}
